# Setting up environment variables

source ~/.env
source ~/.aliases
source ~/.extra # generated by ./install.sh

# Customising terminal prompt
# using pure-prompt
# https://github.com/sindresorhus/pure

autoload -U promptinit; promptinit
prompt pure

# Setup homebrew auto-completions
# https://docs.brew.sh/Shell-Completion

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi
source $HOME/.cargo/env
source ~/.zsh-nvm/zsh-nvm.plugin.zsh
# ~Zsh syntax highlighting

source $HOME/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export PATH="/usr/local/opt/ruby/bin:$PATH"

export PATH="$HOME/.poetry/bin:$PATH"

# Deno Version Manager
export DVM_DIR="$HOME/.dvm"
export PATH="$PATH:$DVM_BIN"
[ -f "$DVM_DIR/dvm.sh" ] && . "$DVM_DIR/dvm.sh"
[ -f "$DVM_DIR/bash_completion" ] && . "$DVM_DIR/bash_completion"

