# Setting up environment variables

source ~/.env
source ~/.aliases
source ~/.extra # generated by ./install.sh

# Customising terminal prompt
# using pure-prompt
# https://github.com/sindresorhus/pure

autoload -U promptinit; promptinit
prompt pure

# Setup homebrew auto-completions
# https://docs.brew.sh/Shell-Completion

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

# NVM setup
# https://github.com/nvm-sh/nvm#installing-and-updating
# that line also exists in ./setup/node.sh

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# ~Zsh syntax highlighting

source $HOME/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
